on:
  pull_request:
  push:
    branches:
      - main

name: Merge checks

jobs:
  check:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Only
        uses: shalzz/zola-deploy-action@v0.22.1
        env:
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts
